### ISSUE TITLE
Remove styles command not working on Windows.

### ISSUE THREAD

**Issue by ackzell** [rakibdev/material-code#2] opened 2022-03-30 20:42 UTC
Hi, 

Thanks for sharing your work @rakibdev !

Unfortunately I was not able to use your "remove styles" command and all my themes were stuck with the rounded styled tabs and buttons with the ripple effect on the clickable items.

I had to go into my Windows installation folder for VSCode and manually remove the code this extension adds to:

```
 C:\Users\{userName}\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-browser\workbench\workbench.html 
```

I don't know if this is a regular practice for extensions to update those files but being honest I don't feel right with the approach.

In any case this is the only way I was able to solve it and VSCode still complained that my installation was corrupted.

**Comment by RicardoMoraisPOR** [comment] 2022-06-03 12:03
+1

**Comment by rakibdev** [comment] 2022-07-10 11:59
@ackzell
Hi, I checked in both Windows, Ubuntu. Unable to reproduce this issue. Error logs should show in Visual Studio Code DevTools. Can I get those?

> I don't feel right with the approach

This is only way I find. This method used by popular ["Custom CSS and JS loader"](https://github.com/be5invis/vscode-custom-css/blob/master/src/extension.js#L129) and ["Synthwave"](https://github.com/robb0wen/synthwave-vscode/blob/master/src/extension.js#L67) extension.  Therefore, kept it optional. I will add in README "This modifies installation workbench.html file. And workbench.html resets after each update."

> still complained that my installation was corrupted

[Checksums in product.json also have to be updated](https://github.com/rakibdev/material-code/blob/main/extension.js#L387) using ["Fix VSCode Checksums"](https://marketplace.visualstudio.com/items?itemName=lehni.vscode-fix-checksums) extension if manually editing workbench.html

**Comment by ackzell** [comment] 2022-07-13 21:46
Thanks for getting back at me @rakibdev 

I uninstalled the theme and haven't added it back since.

Adding the note to the README seems like a good move. Thanks for the links!

**Closed** 2022-07-25 16:10 UTC
